### ISSUE TITLE
Complete the guide to legal docs checklist for all Triquetrum features

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#134]
The checklist at https://wiki.eclipse.org/Development_Resources/HOWTO/Release_Reviews#Checklist states:

> Every bundles contains an about.html file as required by [A Guide to the Legal Documentation for Eclipse-Based Content](https://www.eclipse.org/legal/guidetolegaldoc.php).

The guide to legal documentation has a Feature Checklist

- [x] Every feature has the standard SUA in HTML in "license.html"
- [x] Every feature has the Project’s primary license(s) (e.g., typically the EPL in "epl-v10.html")
- [x] Every feature has the standard SUA in plain text in "feature.xml <license>" or "feature.properties / license"
- [x] Every feature plug-in has copyright notices, etc. in the "blurb" property of "about.properties"

**Comment by cxbrooks** [comment]
I believe that this work is complete, but  checking would be a good thing.

**Comment by cxbrooks** [comment]
Check that features that depend on ptolemy jars have the Ptolemy license.

**Comment by erwindl0** [comment]
The last task in the list above, about a blurb and about.properties seems to have a quite complex background story about feature.properties, a branding plugin, content for the Eclipse Help Installation Details etc.

Some more info can be found at : 

- http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fabout_customization.html
- https://ekkescorner.wordpress.com/2010/06/13/brand-your-feature-and-be-part-of-about-eclipse/
- https://www.eclipse.org/forums/index.php/t/736778/
- section "4.3 Features Licenses and Feature Update Licenses" of https://www.eclipse.org/legal/guidetolegaldoc.php#LegalDoc

I'm trying to refactor the feature.xml to use a feature.properties file, to add missing licenses etc, and to add the about.ini & about.properties files in the corresponding principal plugins.

**Comment by erwindl0** [comment]
I've also added a short section linking to Ptolemy II copyright info in the license.html of the ptolemy feature.

> Third Party Content
> The Content includes items that have been sourced from third parties as set out below. If you did not receive this Content directly from the Eclipse Foundation, the following is provided for informational purposes only, and you should look to the Redistributor’s license for terms and conditions of use. 
> Ptolemy II 11.0.0
> 
> Ptolemy II is released under the fairly liberal UC Berkeley copyright, see http://ptolemy.eecs.berkeley.edu/ptIIcopyright.htm
>  Ptolemy II is free for academic and commercial use. You an incorporate it into products, but you need to follow the instructions in the copyright notice.
> 
> See http://ptolemy.eecs.berkeley.edu/ptolemyII/ptIIfaq.htm#ptolemy%20II%20copyright for more details.

Alternatively, might it not be better to move the ptolemy.feature project to the ptII repo altogether and provide that from the ptII p2 repo?

**Comment by erwindl0** [comment]
I think this is finalized now. Christopher, do you want to close this issue?

**Comment by cxbrooks** [comment]
We could move the ptolemy.feature project to the ptII osgi-2-0 branch, but I think what we have now works in the near term.

I'm closing this one.
